name: Deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 139.59.91.25
          username: root
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd test-mono-cicd
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart web-app
            pm2 restart ws-server
